language: go
go:
  - 1.1
  - 1.1.1
  - tip

branches:
  only:
    - master

script:
  - go build ./...
  - go fmt ./...
  - go get code.google.com/p/go.tools/cmd/vet
  - go vet ./...
  - go test -i -race ./...
  - go test -v -race ./...
